apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: parker-blazor
  name: parker-grafana-deployment
  labels:
    app: parker-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parker-grafana
  template:
    metadata:
      labels:
        app: parker-grafana
    spec:
      containers:
      - name: parker-grafana
        image: grafana/grafana:9.4.7
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"