apiVersion: 1

datasources:
  # - name: prometheus
  #   type: prometheus
  #   uid: prometheus
  #   access: proxy
  #   url: http://prometheus:9090
  #   jsonData:
  #     timeInterval: 10s
  #   basicAuth: false
  #   isDefault: true
  #   version: 1
  #   editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://parker-loki-svc:3100
    basicAuth: false
    version: 1
    editable: false