{
 "title": "Advanced Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current viewing of Occasions",
   "type": "barchart",
   "description": "The up down counter for the occasion service to see which pages are getting more traffic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "OccasionUpDown{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasions Gauge from 0 - 1000",
   "type": "gauge",
   "description": "The amount of occasions that are being viewed during the set time period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(Occasion[30d])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Histogram Quantile of hist variable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, OccasionHist_bucket * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasion Up Down Counter",
   "type": "stat",
   "description": "Views how many occasions are being viewed at specified intervals of time on the site.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(OccasionObservableUpDown[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of HTTP server requests for last hour",
   "type": "timeseries",
   "description": "The sum of all the http server requests that the metric collection is getting, mostly it hitting the health check every so often",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_bucket{job=\"metric-collection\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}