{
 "title": "Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Occasion Hist",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "OccasionHist_bucket{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasion Observable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "OccasionObservable{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasion Up Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "OccasionUpDown{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasion Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "Occasion{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasion Observable Up Down",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "OccasionObservableUpDown{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Occasion Gauge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "OccasionGauge{job=\"metric-collection\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}