name: BackupDatabase
on:
    - workflow_dispatch
jobs:
    backup:
        runs-on: parkertwo
        steps:
            - name: backup
              run: |
                CONTAINER_NAME=$(kubectl -n parker-blazor get pods --no-headers -o custom-columns=":metadata.name" grep "blazor-web-db-deployment")
                kubectl -n parker-blazor exec -t $CONTAINER_NAME -- \
                  pg_dumpall -c -U postgres \
                  > /home/parker/actions-runners/TicketsAreUs/Dump/dump.sql 