name: ParkerRunner
on: [push]
    
jobs:
  Deploy:
    runs-on:
      - parker

    steps:
    #   - name: "clean" 
    #     run: |  
    #       docker compose down -v || true
    #       cd ../../
    #       rm -rf ./ticketsrus-cort-enoch-parker
    #     working-directory: ./../../../ticketsrus-cort-enoch-parker/ParkerStaging

      - name: "clone"
        run: |
          dotnet clean
          dotnet format
          git clone https://${{secrets.PARKER_GITHUB_KEY}}@github.com/SnowSE/ticketsrus-cort-enoch-parker.git
        working-directory: ./../../../

      - name: "build"
        run: |
          
          docker compose up --build -d
        working-directory: ./../../../ticketsrus-cort-enoch-parker/ParkerStaging

  success:
    name: Success
    runs-on: parker
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: success()
        with:
          webhook_url: ${{ secrets.PARKER_TEAMS_HOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `Overwrote title in ${workflow_link}`}"

  if_failure:
    name: Failure
    runs-on: parker
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.PARKER_TEAMS_HOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `Overwrote title in ${workflow_link}`}"




