name: ParkerRunner
on: [push]
    
jobs:
  Deploy:
    runs-on:
      - parker

    steps:
      - name: "clean" 
        run: |  
          docker compose down -v
          cd ../../
          pwd
          rm -rf ./TicketsAreUs
        working-directory: ./../../../TicketsAreUs/ParkerStaging

      - name: "clone"
        run: |
          pwd
          git clone https://${{secrets.PARKER_GITHUB_KEY}}@github.com/ParkerS00/TicketsAreUs.git
        working-directory: ./../../../

      - name: "build"
        run: |
          docker compose up --build -d
        working-directory: ./../../../TicketsAreUs/ParkerStaging

      - name: "lint"
        run: |
          dotnet format --verify-no-changes
        working-directory: ./../../../TicketsAreUs/WebApp

      - name: "unit test"
        run: |

      - name: Teams notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.PARKER_TEAMS_HOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `Overwrote title in ${workflow_link}`}"

