name: ParkerRunner
on: [push]
    
jobs:
  Deploy:
    runs-on:
      - parker
    steps:
      - name: "clean" 
        run: |  
          docker compose down -v
          cd ../../
          rm -rf ./ticketsrus-cort-enoch-parker
        working-directory: ./../../../ticketsrus-cort-enoch-parker/ParkerStaging
        #

      - name: "clone"
        run: |
          pwd
          git clone https://${{secrets.PARKER_GITHUB_KEY}}@github.com/SnowSE/ticketsrus-cort-enoch-parker.git
        working-directory: ./../../../

      - name: "build"
        run: |
          docker compose up --build -d
        working-directory: ./../../../ticketsrus-cort-enoch-parker/ParkerStaging

      - name: "lint"
        run: |
          dotnet format --verify-no-changes
        working-directory: ./../../../ticketsrus-cort-enoch-parker/WebApp

      - name: "unit test"
        run: |
          dotnet test
      working-directory: ./../../../ticketsrus-cort-enoch-parker/Test  

      - name: Teams notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.PARKER_TEAMS_HOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `Overwrote title in ${workflow_link}`}"

