name: PullRequest
on: 
    pull_request: 
      types: [opened]
jobs:
    deploy-to-kubernetes:
      runs-on: parkertwo
      steps:
        - name: check out code
          uses: actions/checkout@v4
        - name: deploy kubernetes environment
          run: |
            export PULL_REQUEST_ID=${{github.event.pull_request.number}}
            kubectl create namespace parker-pr-$PULL_REQUEST_ID